#!/bin/bash
#SBATCH --job-name=psd_app
#SBATCH --partition=brainlife
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10          # use 10 CPU cores
#SBATCH --time=00:30:00             # walltime 30 minutes (adjust if needed)
#SBATCH --mem-per-cpu=4G             # memory per CPU core, adjust as needed

# Optional: output & error files
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err


#bl2bids

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_psd_grad
mkdir -p out_psd_mag
mkdir -p out_psd_eeg
mkdir -p out_figs

#python main.py
singularity exec docker://brainlife/mne:0.23dev python3 main.py

# Store PSD plot with alpha peak on product.json
cat << EOF > product.json
{
    "brainlife": [
       { 
           "type": "image/png", 
	       "name": "Power Spectral Density",
           "base64": "$(base64 -w 0 out_figs/psd_mne.png)"
       },
       { 
           "type": "image/png", 
	       "name": "computed PSD",
           "base64": "$(base64 -w 0 out_figs/psd_computed.png)"
       }
]
}
EOF



